language: go
go:
  - 1.4
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
install:
  - make updatedeps
script:
  - go test -v ./...
before_install:
  - go get github.com/mitchellh/gox
  - gox -build-toolchain
  - go get github.com/tcnksm/ghr
after_success:
  - make ci
  - ghr --username ojongerius --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
