language: go
go:
  - 1.4
  - tip
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
install:
  - make updatedeps
script:
  - go test -v ./...
before_install:
   - go get github.com/mitchellh/gox
after_success:
  - make bin
